# Generated by Django 5.2 on 2025-04-14 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название зала')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='halls_images/', verbose_name='Изображение')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Теги')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('capacity_min', models.PositiveIntegerField(default=0, verbose_name='Мин. вместимость')),
                ('capacity_max', models.PositiveIntegerField(default=0, verbose_name='Макс. вместимость')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('food_option', models.CharField(choices=[('venue', 'От заведения'), ('own', 'Своя')], default='venue', max_length=10, verbose_name='Еда')),
                ('alcohol_option', models.CharField(choices=[('allowed', 'Разрешено'), ('forbidden', 'Запрещено')], default='allowed', max_length=10, verbose_name='Алкоголь')),
                ('event_types', models.CharField(blank=True, max_length=255, verbose_name='Типы мероприятий')),
                ('service', models.TextField(blank=True, verbose_name='Обслуживание')),
                ('rules', models.TextField(blank=True, verbose_name='Правила')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
    ]
