# Generated by Django 5.2 on 2025-04-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='service',
            field=models.BooleanField(default=False, verbose_name='Обслуживание'),
        ),
    ]
