# Generated by Django 5.2 on 2025-04-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_hallimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HallImage',
        ),
    ]
