# Generated by Django 5.2 on 2025-04-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0006_hallimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HallImage',
        ),
    ]
