# Generated by Django 5.2 on 2025-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_payment_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
