# Generated by Django 5.2 on 2025-05-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0011_booking_is_payment_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
