# Generated by Django 5.2 on 2025-05-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0013_message_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
    ]
