# Generated by Django 5.2 on 2025-05-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0015_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
